name: Build macOS gccgfortran

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update packages
      run: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install autoconf automake coreutils gcc@9 libtool mpich gnu-sed wget cmake git
    - name: Build NCEPLIBS-external
      run: |
        export CC=gcc-9
        export FC=gfortran-9
        export CXX=g++-9
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=$PWD/../install .. 2>&1 | tee log.cmake
        make -j8 2>&1 | tee log.make
        cd ..
        ls -l install/bin/ESMF_Info
        ls -l install/bin/wgrib2
        cat install/share/nceplibs-external.cmake.config
